# ------------------------------------------------------------------------------------
#  Super-Linter Workflow
#
#  Purpose  : Runs GitHub's Super-Linter against the files that have changed on every
#             push to, or pull request against, the default branch.  The linter set
#             is tailored to this repository so we don’t waste minutes on unrelated
#             languages / tools.
#
#  Docs     : https://github.com/github/super-linter
#  Created  : 2025-04-23
#  Maintainer: @your-team-alias
# ------------------------------------------------------------------------------------

name: super-linter

#######################################################################################
# EVENT TRIGGERS
#
# • We lint every PR so contributors get immediate feedback.
# • We also lint direct pushes to the default branch – useful for
#   admin hot-fixes that bypass PR review in an emergency.
#
#   NOTE: If your main branch is called "main", update the branch filters below
#   and the DEFAULT_BRANCH env var further down.
#######################################################################################
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

#######################################################################################
# GLOBAL PERMISSIONS
#   • The job only needs read access to the repository’s code to calculate diffs and
#     report annotations.  Keep permissions minimal to adhere to the principle of
#     least privilege.
#######################################################################################
permissions:
  contents: read

jobs:
  run-lint:
    # -------------------------------------------------------------------------------
    #  RUNTIME
    #
    # • ubuntu-latest → always maps to the most recent LTS runner.
    #   Super-Linter uses Docker, so container support is essential.
    # -------------------------------------------------------------------------------
    runs-on: ubuntu-latest

    # -------------------------------------------------------------------------------
    #  CONCURRENCY
    #
    # • Cancel any previous lint run for the same branch / PR.
    #   This avoids wasting runner minutes when devs push multiple updates quickly.
    # -------------------------------------------------------------------------------
    concurrency:
      group: super-linter-${{ github.ref }}
      cancel-in-progress: true

    steps:
      # ---------------------------------------------------------------------------
      # 1) Checkout repository
      #
      # • We need the *full* history so Super-Linter can figure out which files
      #   actually changed (diff-based linting).  fetch-depth: 0 does that.
      # ---------------------------------------------------------------------------
      - name: 🚚  Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Full history for proper diff detection

      # ---------------------------------------------------------------------------
      # 2) Run Super-Linter
      #
      # • Only enable the linters we actively care about – the rest are disabled to
      #   shorten CI time and avoid noise.  Every option is documented inline.
      #
      # • DEFAULT_BRANCH must match the branch defined in the "on:" trigger above.
      #
      # • VALIDATE_ALL_CODEBASE=false → Lint only the changed files for
      #   faster feedback loops.  Set to true periodically (e.g., nightly)
      #   if you want to catch legacy issues.
      # ---------------------------------------------------------------------------
      - name: 🧹  Lint Code Base
        uses: github/super-linter@v7
        env:
          # -------- Super-Linter core variables -----------------------------------
          DEFAULT_BRANCH: master          # Update if you rename your default branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # -------- Scope control -----------------------------------------------
          VALIDATE_ALL_CODEBASE: false    # true runs every file – great for cron jobs

          # -------- Disabled linters --------------------------------------------
          # Keep this list sorted alphabetically for readability.
          # If you enable a linter later, remove its flag or set it to "true".
          VALIDATE_CHECKOV: false             # Terraform security scanning – N/A
          VALIDATE_EDITORCONFIG: false        # Not enforced in this repo
          VALIDATE_GO: false                  # Handled in a dedicated Go test workflow
          VALIDATE_GO_MODULES: false          # Ditto
          VALIDATE_GO_RELEASER: false         # v2 syntax unsupported
          VALIDATE_JSCPD: false               # Duplicate-code checker – opt-out
          VALIDATE_JSON_PRETTIER: false       # Formatting handled by Prettier locally
          VALIDATE_MARKDOWN: false            # Turn on if MD linting becomes useful
          VALIDATE_MARKDOWN_PRETTIER: false   # Markdown formatting – skipped
          VALIDATE_YAML_PRETTIER: false       # YAML formatting – skipped
